package io.github.msh91.arch

object Versions {
    const val arrow = "1.2.0"
    const val gradle = "7.4.2"
    const val ktlint = "1.1.1"
    const val kotlin = "1.9.22"
    const val coroutines = "1.6.4"
    const val lifecycle = "2.7.0"
    const val archTest = "2.2.0"
    const val material = "1.11.0"
    const val constraintLayout = "2.1.4"
    const val room = "2.6.1"
    const val dagger = "2.50"
    const val okHttp = "4.11.0"
    const val gson = "2.8.6"
    const val retrofit = "2.9.0"
    const val junit = "4.12"
    const val testRunner = "1.2.0"
    const val espresso = "3.4.0"
    const val mockk = "1.13.8"
    const val navigationComponent = "2.5.3"
    const val fragment = "1.5.5"
    const val anyChart = "1.1.5"
}
